spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql:///graphqltest?characterEncoding=utf-8&useSSL=false&useTimezone=true
#    url: jdbc:mysql:///sell?characterEncoding=utf-8&useSSL=false&useTimezone=true

  jpa:
    hibernate:
      ddl-auto: update


#  main:
#    allow-bean-definition-overriding: true

  redis:
    host: 192.168.1.151
    port: 6379

server:
  port: 8081

#GraphQL api 浏览器端调试工具
graphiql:
  enabled: true
  endpoint: /graphql
  mapping: /graphiql

#GraphQL api PC桌面调试工具
graphql:
  servlet:
    corsEnabled: true
    enabled: true
    mapping: /graphql
